app:
    init: true
    maintain: false
    public_base_api_url: # when local applied
    public_data_url: # when s3 applied, used generate urls for accessing media

storage:
    type:
        audio:
            provider: local # local | s3
            bucket: ''
        static:
            provider: s3 # local | s3
            bucket: ''
    library_dir: # for local storage
    cache_dir: # for local storage for cache storage. deleted later
    #s3 sdk
    s3: # used for generate presigned urls
        region: 'auto'
        endpoint: ''

# not used yet
ffmpeg:
    ffmpeg_path: ffmpeg
    ffprobe_path: ffprobe

security:
    token:
        # change to your domain
        issuer: 'http://localhost'
        audience: 'music-app'
    cookies:
        # change to your domain
        domain: 'localhost'
    cors:
        enabled: true
        # add your domain
        origin:
            - http://localhost:3000
            - http://localhost:3100
            - http://localhost:5000
