/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/albums": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateAlbumRequest"][];
                    "text/json": components["schemas"]["CreateAlbumRequest"][];
                    "application/*+json": components["schemas"]["CreateAlbumRequest"][];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CreateAlbumResult"][];
                        "application/json": components["schemas"]["CreateAlbumResult"][];
                        "text/json": components["schemas"]["CreateAlbumResult"][];
                    };
                };
                /** @description Multi-Status */
                207: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CreateAlbumResult"][];
                        "application/json": components["schemas"]["CreateAlbumResult"][];
                        "text/json": components["schemas"]["CreateAlbumResult"][];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                    "text/json": components["schemas"]["LoginRequest"];
                    "application/*+json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LoginResponse"];
                        "application/json": components["schemas"]["LoginResponse"];
                        "text/json": components["schemas"]["LoginResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreatePartyRequest"];
                    "text/json": components["schemas"]["CreatePartyRequest"];
                    "application/*+json": components["schemas"]["CreatePartyRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parties/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Search?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PartyListModel"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AlbumCreditRequest: {
            /** Format: int32 */
            partyId: number | string;
            credit: components["schemas"]["AlbumCreditType"];
        };
        /** @enum {unknown} */
        AlbumCreditType: "Artist";
        AlbumDiscRequest: {
            /** Format: int32 */
            discNumber: number | string;
            subtitle?: string;
            tracks: components["schemas"]["AlbumTrackRequest"][];
        };
        AlbumImageRequest: {
            file: components["schemas"]["FileRequest"];
            description?: string;
            fileCroppedArea?: null | components["schemas"]["FileCroppedArea"];
        };
        AlbumTrackRequest: {
            /** Format: int32 */
            trackNumber: number | string;
            title: string;
            description?: string;
            isMC?: boolean;
            /** Format: int32 */
            durationInMs: number | string;
            /** Format: int32 */
            languageId?: null | number | string;
            trackCredits: components["schemas"]["TrackCreditRequest"][];
            trackVariants: components["schemas"]["TrackVariantRequest"][];
        };
        /** @enum {unknown} */
        AlbumType: "Album" | "Single" | "Compilation" | "Live" | "Soundtrack" | "Remix" | "Other";
        CreateAlbumImageUploadItemResult: {
            blake3Id: string;
            fileName: string;
            uploadUrl: string;
        };
        CreateAlbumRequest: {
            title: string;
            description?: string;
            type: components["schemas"]["AlbumType"];
            /** Format: int32 */
            languageId?: null | number | string;
            /** Format: date-time */
            releaseDate?: null | string;
            albumCredits: components["schemas"]["AlbumCreditRequest"][];
            albumImage?: null | components["schemas"]["AlbumImageRequest"];
            discs: components["schemas"]["AlbumDiscRequest"][];
        };
        CreateAlbumResult: {
            albumTitle: string;
            isSuccess?: boolean;
            errorMessage?: null | string;
            createAlbumUploadResults?: null | components["schemas"]["CreateAlbumUploadResult"];
        };
        CreateAlbumTrackUploadItemResult: {
            blake3Id: string;
            fileName: string;
            multipartUploadInfo: components["schemas"]["MultipartUploadInfo"];
        };
        CreateAlbumUploadResult: {
            albumTitle: string;
            albumImage?: null | components["schemas"]["CreateAlbumImageUploadItemResult"];
            tracks?: components["schemas"]["CreateAlbumTrackUploadItemResult"][];
        };
        CreatePartyRequest: {
            name: string;
            partyType: components["schemas"]["PartyType"];
            /** Format: int32 */
            languageId?: number | string;
            cover?: null | components["schemas"]["PartyImageRequest"];
            banner?: null | components["schemas"]["PartyImageRequest"];
        };
        FileCroppedArea: {
            /** Format: int32 */
            width: number | string;
            /** Format: int32 */
            height: number | string;
            /** Format: int32 */
            x: number | string;
            /** Format: int32 */
            y: number | string;
        };
        FileRequest: {
            fileBlake3: string;
            fileSHA1: string;
            mimeType: string;
            /** Format: int64 */
            fileSizeInBytes: number | string;
            container: string;
            extension: string;
            codec?: null | string;
            /** Format: int32 */
            width?: null | number | string;
            /** Format: int32 */
            height?: null | number | string;
            /** Format: int32 */
            audioSampleRate?: null | number | string;
            /** Format: int32 */
            bitrate?: null | number | string;
            /** Format: double */
            frameRate?: null | number | string;
            /** Format: int32 */
            durationInMs?: null | number | string;
            originalFileName: string;
        };
        LoginRequest: {
            username: string;
            password: string;
        };
        LoginResponse: {
            token: string;
            user: components["schemas"]["UserDto"];
        };
        MultipartUploadInfo: {
            uploadId: string;
            /** Format: int64 */
            partSizeInBytes: number | string;
            parts: components["schemas"]["MultipartUploadPartInfo"][];
        };
        MultipartUploadPartInfo: {
            /** Format: int32 */
            partNumber: number | string;
            url: string;
        };
        PartyAliasModel: {
            aliasName: string;
            aliasNormalizedName: string;
        };
        PartyImageRequest: {
            imageType: components["schemas"]["PartyImageType"];
            image: components["schemas"]["FileRequest"];
            fileCroppedArea?: null | components["schemas"]["FileCroppedArea"];
        };
        /** @enum {unknown} */
        PartyImageType: "Avatar" | "Banner";
        PartyListModel: {
            /** Format: int32 */
            partyId: number | string;
            partyName: string;
            partyNormalizedName: string;
            partyAliases: components["schemas"]["PartyAliasModel"][];
        };
        /** @enum {unknown} */
        PartyType: "Individual" | "Group" | "Project";
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
        };
        TrackCreditRequest: {
            /** Format: int32 */
            partyId: number | string;
            credit: components["schemas"]["TrackCreditType"];
        };
        /** @enum {unknown} */
        TrackCreditType: "Artist";
        /** @enum {unknown} */
        TrackSource: "MORA" | "OTOTOY" | "CD" | "BluRay" | "Vinyl" | "YouTube" | "SoundCloud" | "OTHER";
        TrackSourceRequest: {
            source: components["schemas"]["TrackSource"];
            file: components["schemas"]["FileRequest"];
        };
        TrackVariantRequest: {
            variantType: components["schemas"]["TrackVariantType"];
            sources: components["schemas"]["TrackSourceRequest"][];
        };
        /** @enum {unknown} */
        TrackVariantType: "Default" | "Instrumental";
        UserDto: {
            id: string;
            userName: string;
            roles: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
