/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/albums/{id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AlbumSummary"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/albums": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Search?: string;
                    Types?: components["schemas"]["AlbumType"][];
                    LanguageIds?: (number | string)[];
                    PartyIds?: (number | string)[];
                    IsIncludeInTrackCredit?: boolean;
                    Sort?: components["schemas"]["ListSortOption"];
                    Limit?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AlbumListItem"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateAlbumRequest"][];
                    "text/json": components["schemas"]["CreateAlbumRequest"][];
                    "application/*+json": components["schemas"]["CreateAlbumRequest"][];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CreateAlbumResult"][];
                        "application/json": components["schemas"]["CreateAlbumResult"][];
                        "text/json": components["schemas"]["CreateAlbumResult"][];
                    };
                };
                /** @description Multi-Status */
                207: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CreateAlbumResult"][];
                        "application/json": components["schemas"]["CreateAlbumResult"][];
                        "text/json": components["schemas"]["CreateAlbumResult"][];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CreateAlbumResult"][];
                        "application/json": components["schemas"]["CreateAlbumResult"][];
                        "text/json": components["schemas"]["CreateAlbumResult"][];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/albums/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AlbumDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                    "text/json": components["schemas"]["LoginRequest"];
                    "application/*+json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LoginResult"];
                        "application/json": components["schemas"]["LoginResult"];
                        "text/json": components["schemas"]["LoginResult"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/bot-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuthSessionDto"][];
                        "application/json": components["schemas"]["AuthSessionDto"][];
                        "text/json": components["schemas"]["AuthSessionDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/passkey-request-options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    username?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["JsonElement"];
                        "application/json": components["schemas"]["JsonElement"];
                        "text/json": components["schemas"]["JsonElement"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/passkey-signin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["JsonElement"];
                    "text/json": components["schemas"]["JsonElement"];
                    "application/*+json": components["schemas"]["JsonElement"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LoginResult"];
                        "application/json": components["schemas"]["LoginResult"];
                        "text/json": components["schemas"]["LoginResult"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/passkey-creation-options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/passkey-register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["JsonElement"];
                    "text/json": components["schemas"]["JsonElement"];
                    "application/*+json": components["schemas"]["JsonElement"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PasskeyDto"];
                        "application/json": components["schemas"]["PasskeyDto"];
                        "text/json": components["schemas"]["PasskeyDto"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/passkeys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PasskeyEditRequest"];
                    "text/json": components["schemas"]["PasskeyEditRequest"];
                    "application/*+json": components["schemas"]["PasskeyEditRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PasskeyDeleteRequest"];
                    "text/json": components["schemas"]["PasskeyDeleteRequest"];
                    "application/*+json": components["schemas"]["PasskeyDeleteRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/concerts/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateConcertRequest"];
                    "text/json": components["schemas"]["CreateConcertRequest"];
                    "application/*+json": components["schemas"]["CreateConcertRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CreateConcertUploadResult"];
                        "application/json": components["schemas"]["CreateConcertUploadResult"];
                        "text/json": components["schemas"]["CreateConcertUploadResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/concerts/create-without-upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateConcertRequest"];
                    "text/json": components["schemas"]["CreateConcertRequest"];
                    "application/*+json": components["schemas"]["CreateConcertRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CreateConcertWithoutUploadResult"];
                        "application/json": components["schemas"]["CreateConcertWithoutUploadResult"];
                        "text/json": components["schemas"]["CreateConcertWithoutUploadResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/concerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Search?: string;
                    PartyIds?: (number | string)[];
                    IsIncludeInGuestCredit?: boolean;
                    Sort?: components["schemas"]["ListSortOption"];
                    Limit?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ConcertListItem"][];
                        "application/json": components["schemas"]["ConcertListItem"][];
                        "text/json": components["schemas"]["ConcertListItem"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/concerts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ConcertDetails"];
                        "application/json": components["schemas"]["ConcertDetails"];
                        "text/json": components["schemas"]["ConcertDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{id}/play": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{id}/manifest.mpd": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/dash+xml": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/{id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/languages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LanguageListItem"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserInfo"];
                        "application/json": components["schemas"]["UserInfo"];
                        "text/json": components["schemas"]["UserInfo"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Search?: string;
                    Country?: components["schemas"]["CountryCode"];
                    Type?: components["schemas"]["PartyType"];
                    Kind?: components["schemas"]["PartyKind"];
                    Gender?: components["schemas"]["PartyGender"];
                    ExcludeNoAlbums?: boolean;
                    Sort?: components["schemas"]["ListSortOption"];
                    Limit?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PartyItems"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreatePartyRequest"];
                    "text/json": components["schemas"]["CreatePartyRequest"];
                    "application/*+json": components["schemas"]["CreatePartyRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreatePartyResult"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parties/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PartyDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    Query?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SearchResult"];
                        "application/json": components["schemas"]["SearchResult"];
                        "text/json": components["schemas"]["SearchResult"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/opensearch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/Init": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateUploadRequest"];
                    "text/json": components["schemas"]["CreateUploadRequest"];
                    "application/*+json": components["schemas"]["CreateUploadRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MultipartUploadResults"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PendingOriginalFileResult"][];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/{fileObjectId}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    fileObjectId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StartUploadResult"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CompleteUploadRequest"];
                    "text/json": components["schemas"]["CompleteUploadRequest"];
                    "application/*+json": components["schemas"]["CompleteUploadRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserInfo"][];
                        "application/json": components["schemas"]["UserInfo"][];
                        "text/json": components["schemas"]["UserInfo"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateUserRequest"];
                    "text/json": components["schemas"]["CreateUserRequest"];
                    "application/*+json": components["schemas"]["CreateUserRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserInfo"];
                        "application/json": components["schemas"]["UserInfo"];
                        "text/json": components["schemas"]["UserInfo"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateUserRequest"];
                    "text/json": components["schemas"]["UpdateUserRequest"];
                    "application/*+json": components["schemas"]["UpdateUserRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserInfo"];
                        "application/json": components["schemas"]["UserInfo"];
                        "text/json": components["schemas"]["UserInfo"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/workers/concert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RerunConcertWorkerRequest"];
                    "text/json": components["schemas"]["RerunConcertWorkerRequest"];
                    "application/*+json": components["schemas"]["RerunConcertWorkerRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workers/party": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RerunPartyInfoEnrichmentWorkerRequest"];
                    "text/json": components["schemas"]["RerunPartyInfoEnrichmentWorkerRequest"];
                    "application/*+json": components["schemas"]["RerunPartyInfoEnrichmentWorkerRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AlbumCoverDetails: {
            album: components["schemas"]["ImageFileVariants"];
            discs: components["schemas"]["AlbumDiscCoverDetails"][];
        };
        AlbumDetails: {
            /** Format: int32 */
            albumId: number | string;
            title: string;
            type: components["schemas"]["AlbumType"];
            /** Format: date-time */
            releaseDate?: null | string;
            /** Format: int32 */
            totalTrackCount: number | string;
            /** Format: int32 */
            totalDurationInMs: number | string;
            cover: components["schemas"]["AlbumCoverDetails"];
            credits: components["schemas"]["AlbumPartyCredit"][];
            discs: components["schemas"]["AlbumDiscDetails"][];
        };
        AlbumDiscCoverDetails: {
            /** Format: int32 */
            albumDiscId: number | string;
            /** Format: int32 */
            discNumber: number | string;
            variants: components["schemas"]["ImageFileVariants"];
        };
        AlbumDiscDetails: {
            /** Format: int32 */
            albumDiscId: number | string;
            /** Format: int32 */
            discNumber: number | string;
            subtitle?: string;
            tracks: components["schemas"]["AlbumTrackDetails"][];
        };
        AlbumDiscRequest: {
            /** Format: int32 */
            discNumber: number | string;
            subtitle?: string;
            image?: null | components["schemas"]["AlbumImageRequest"];
            tracks: components["schemas"]["AlbumTrackRequest"][];
        };
        AlbumImageRequest: {
            clientReferenceId: string;
            file: components["schemas"]["FileRequest"];
            description?: string;
            croppedArea?: null | components["schemas"]["FileCroppedAreaRequest"];
        };
        AlbumListArtist: {
            /** Format: int32 */
            partyId: number | string;
            name: string;
        };
        AlbumListItem: {
            /** Format: int32 */
            albumId: number | string;
            title: string;
            description?: string;
            type: components["schemas"]["AlbumType"];
            /** Format: date-time */
            releaseDate?: null | string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            coverVariants?: components["schemas"]["ImageFileVariants"];
            discCovers?: components["schemas"]["AlbumDiscCoverDetails"][];
            artists: components["schemas"]["AlbumListArtist"][];
            matchedTracks?: components["schemas"]["AlbumListMatchedTrack"][];
            /** Format: int32 */
            trackCount: number | string;
            /** Format: int32 */
            totalDurationInMs: number | string;
        };
        AlbumListMatchedTrack: {
            /** Format: int32 */
            trackId: number | string;
            /** Format: int32 */
            discNumber: number | string;
            /** Format: int32 */
            trackNumber: number | string;
            title: string;
            /** Format: int32 */
            basedOnTrackId?: null | number | string;
            basedOnTrackTitle?: null | string;
        };
        AlbumPartyCredit: {
            /** Format: int32 */
            partyId: number | string;
            name: string;
            type: components["schemas"]["PartyType"];
            creditType: components["schemas"]["CreditType"];
            avatar: components["schemas"]["ImageFileVariants"];
        };
        AlbumSummary: {
            title: string;
            credits: string[];
            coverUrl: string;
        };
        AlbumTrackDetails: {
            /** Format: int32 */
            trackId: number | string;
            /** Format: int32 */
            trackNumber: number | string;
            title: string;
            /** Format: int32 */
            durationInMs: number | string;
            contentType: components["schemas"]["TrackContentType"];
            versionType: components["schemas"]["TrackVersionType"];
            /** Format: int32 */
            basedOnTrackId?: null | number | string;
            credits: components["schemas"]["TrackPartyCredit"][];
            audios: components["schemas"]["TrackAudioDetails"][];
        };
        AlbumTrackRequest: {
            clientTempTrackId: string;
            /** Format: int32 */
            trackNumber: number | string;
            title: string;
            description?: string;
            /** Format: int32 */
            durationInMs: number | string;
            /** Format: int32 */
            languageId?: null | number | string;
            contentType?: components["schemas"]["TrackContentType"];
            versionType?: components["schemas"]["TrackVersionType"];
            /** Format: int32 */
            basedOnTrackId?: null | number | string;
            credits: components["schemas"]["CreditRequest"][];
            audios: components["schemas"]["TrackAudioRequest"][];
        };
        /** @enum {unknown} */
        AlbumType: "Album" | "Single" | "Compilation" | "Live" | "Soundtrack" | "Remix" | "Other";
        AuthSessionDto: {
            /** Format: uuid */
            id: string;
            last5Digit: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            expiresAt: null | string;
            /** Format: date-time */
            lastUsedAt: null | string;
            isCurrent: boolean;
        };
        CompleteMultipartUploadPart: {
            /** Format: int32 */
            partNumber: number | string;
            eTag: string;
        };
        CompleteMultipartUploadRequest: {
            uploadId: string;
            parts: components["schemas"]["CompleteMultipartUploadPart"][];
        };
        CompleteUploadRequest: {
            /** Format: uuid */
            fileObjectId: string;
            multipart?: null | components["schemas"]["CompleteMultipartUploadRequest"];
        };
        ConcertDetails: {
            /** Format: int32 */
            concertId: number | string;
            title: string;
            description?: string;
            /** Format: date-time */
            date?: null | string;
            coverVariants: components["schemas"]["ImageFileVariants"];
            linkedParties: components["schemas"]["ConcertPartySummary"][];
            linkedAlbums: components["schemas"]["AlbumListItem"][];
            files: components["schemas"]["ConcertFileDetails"][];
            /** Format: int32 */
            totalDurationInMs: number | string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ConcertFileDetails: {
            /** Format: int32 */
            concertFileId: number | string;
            title: string;
            type: components["schemas"]["ConcertFileType"];
            /** Format: int32 */
            order: number | string;
            source: components["schemas"]["MediaSource"];
            sourceUrl?: null | string;
            file: components["schemas"]["ConcertFileVariants"];
        };
        ConcertFileRequest: {
            title: string;
            type: components["schemas"]["ConcertFileType"];
            /** Format: int32 */
            order?: number | string;
            source?: components["schemas"]["MediaSource"];
            sourceUrl?: null | string;
            simpleBlake3Hash: string;
            mimeType: string;
            /** Format: int64 */
            sizeInBytes: number | string;
            originalFileName: string;
        };
        /** @enum {unknown} */
        ConcertFileType: "Performance" | "BehindTheScenes" | "Extra" | "Other";
        ConcertFileVariants: {
            original: components["schemas"]["FileObjectDetails"];
            originalDash?: null | components["schemas"]["FileObjectDetails"];
            remuxedOriginal?: null | components["schemas"]["FileObjectDetails"];
            dashAV1?: null | components["schemas"]["FileObjectDetails"];
            thumbnail640x360?: null | components["schemas"]["FileObjectDetails"];
            attachedPicture?: null | components["schemas"]["FileObjectDetails"];
            subtitleVtt: components["schemas"]["FileObjectDetails"][];
            subtitleSup: components["schemas"]["FileObjectDetails"][];
        };
        ConcertImageRequest: {
            file: components["schemas"]["FileRequest"];
            croppedArea?: null | components["schemas"]["FileCroppedAreaRequest"];
        };
        ConcertListItem: {
            /** Format: int32 */
            concertId: number | string;
            title: string;
            /** Format: double */
            similarity?: number | string;
            description?: string;
            /** Format: date-time */
            date?: null | string;
            coverVariants: components["schemas"]["ImageFileVariants"];
            parties: components["schemas"]["ConcertPartySummary"][];
            /** Format: int32 */
            albumCount: number | string;
            /** Format: int32 */
            fileCount: number | string;
            /** Format: int32 */
            totalDurationInMs: number | string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ConcertPartyRequest: {
            /** Format: int32 */
            partyId: number | string;
            role: components["schemas"]["ConcertPartyRole"];
        };
        /** @enum {unknown} */
        ConcertPartyRole: "MainArtist" | "Guest";
        ConcertPartySummary: {
            /** Format: int32 */
            partyId: number | string;
            name: string;
            avatar: components["schemas"]["ImageFileVariants"];
            type: components["schemas"]["PartyType"];
            role: components["schemas"]["ConcertPartyRole"];
        };
        /** @enum {unknown} */
        CountryCode: "XX" | "HK" | "JP" | "KR" | "US" | "CN" | "TW" | "ID";
        CreateAlbumImageUploadItemResult: {
            clientReferenceId: string;
            /** Format: int32 */
            discNumber?: null | number | string;
            /** Format: uuid */
            fileObjectId: string;
            blake3Hash: string;
            fileName: string;
            uploadUrl: string;
        };
        CreateAlbumRequest: {
            clientTempAlbumId: string;
            title: string;
            description?: string;
            type: components["schemas"]["AlbumType"];
            /** Format: int32 */
            languageId?: null | number | string;
            /** Format: date-time */
            releaseDate?: null | string;
            credits: components["schemas"]["CreditRequest"][];
            image?: null | components["schemas"]["AlbumImageRequest"];
            discs: components["schemas"]["AlbumDiscRequest"][];
        };
        CreateAlbumResult: {
            clientTempAlbumId: string;
            albumTitle: string;
            isSuccess?: boolean;
            errorMessage?: null | string;
            upload?: null | components["schemas"]["CreateAlbumUploadResult"];
        };
        CreateAlbumTrackUploadItemResult: {
            /** Format: uuid */
            fileObjectId: string;
            blake3Hash: string;
            fileName: string;
            multipartUploadInfo: components["schemas"]["MultipartUploadResults"];
        };
        CreateAlbumUploadResult: {
            albumTitle: string;
            images?: components["schemas"]["CreateAlbumImageUploadItemResult"][];
            tracks?: components["schemas"]["CreateAlbumTrackUploadItemResult"][];
        };
        CreateConcertRequest: {
            title: string;
            description?: string;
            /** Format: date-time */
            date?: null | string;
            image?: null | components["schemas"]["ConcertImageRequest"];
            linkedAlbumIds?: (number | string)[];
            linkedParties?: components["schemas"]["ConcertPartyRequest"][];
            files?: components["schemas"]["ConcertFileRequest"][];
        };
        CreateConcertUploadImageResult: {
            blake3Hash: string;
            uploadUrl: string;
        };
        CreateConcertUploadItemResult: {
            fileName: string;
            /** Format: uuid */
            fileObjectId: string;
            simpleBlake3Hash: string;
            multipartUploadInfo: components["schemas"]["MultipartUploadResults"];
        };
        CreateConcertUploadResult: {
            concertTitle: string;
            concertImage?: null | components["schemas"]["CreateConcertUploadImageResult"];
            files?: components["schemas"]["CreateConcertUploadItemResult"][];
        };
        CreateConcertWithoutUploadItemResult: {
            fileName: string;
            /** Format: uuid */
            fileObjectId: string;
            simpleBlake3Hash: string;
        };
        CreateConcertWithoutUploadResult: {
            token: string;
            concertImage?: null | components["schemas"]["CreateConcertUploadImageResult"];
            concertTitle: string;
            files?: components["schemas"]["CreateConcertWithoutUploadItemResult"][];
        };
        CreatePartyRequest: {
            name: string;
            type: components["schemas"]["PartyType"];
            kind: components["schemas"]["PartyKind"];
            gender?: components["schemas"]["PartyGender"];
            country: components["schemas"]["CountryCode"];
            musicBrainzID?: null | string;
            avatar?: null | components["schemas"]["PartyImageRequest"];
            banner?: null | components["schemas"]["PartyImageRequest"];
        };
        CreatePartyResult: {
            /** Format: int32 */
            partyId: number | string;
        };
        CreateUploadRequest: {
            /** Format: int32 */
            fileObjectId: number | string;
        };
        CreateUserRequest: {
            username: string;
            password: string;
            role: components["schemas"]["Roles"];
        };
        CreditRequest: {
            /** Format: int32 */
            partyId: number | string;
            credit: components["schemas"]["CreditType"];
        };
        /** @enum {unknown} */
        CreditType: "Artist";
        FileCroppedAreaRequest: {
            /** Format: int32 */
            width: number | string;
            /** Format: int32 */
            height: number | string;
            /** Format: int32 */
            x: number | string;
            /** Format: int32 */
            y: number | string;
        };
        FileObjectDetails: {
            /** Format: uuid */
            id: string;
            url: string;
            variant: components["schemas"]["FileObjectVariant"];
            /** Format: int64 */
            sizeInBytes: number | string;
            mimeType: string;
            container: string;
            extension: string;
            codec?: null | string;
            /** Format: int32 */
            width?: null | number | string;
            /** Format: int32 */
            height?: null | number | string;
            /** Format: int32 */
            audioSampleRate?: null | number | string;
            /** Format: int32 */
            bitrate?: null | number | string;
            /** Format: int32 */
            bitsPerSample?: null | number | string;
            /** Format: double */
            frameRate?: null | number | string;
            /** Format: int32 */
            durationInMs?: null | number | string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @enum {unknown} */
        FileObjectVariant: "Original" | "TaggedOriginal" | "Opus96" | "WaveformB8Pixel20" | "OriginalDash" | "DashAV1" | "Thumbnail640x360" | "AttachedPicture" | "SubtitleVtt" | "SubtitleSup" | "RemuxedOriginal" | "ImageCover1024x1024" | "ImageAvatar512x512" | "ImageBanner1500x500" | "ImageWide1280x720";
        /** @enum {unknown} */
        FileProcessingStatus: "Pending" | "Processing" | "Completed" | "Failed" | "Uploaded";
        FileRequest: {
            blake3Hash: string;
            mimeType: string;
            /** Format: int64 */
            sizeInBytes: number | string;
            container: string;
            extension: string;
            codec?: null | string;
            lossless?: boolean;
            /** Format: int32 */
            audioChannels?: null | number | string;
            /** Format: int32 */
            bitsPerSample?: null | number | string;
            /** Format: int32 */
            width?: null | number | string;
            /** Format: int32 */
            height?: null | number | string;
            /** Format: int32 */
            audioSampleRate?: null | number | string;
            /** Format: int32 */
            bitrate?: null | number | string;
            /** Format: double */
            frameRate?: null | number | string;
            /** Format: int32 */
            durationInMs?: null | number | string;
            originalFileName: string;
        };
        ImageFileVariants: {
            original?: null | components["schemas"]["FileObjectDetails"];
            imageCover1024x1024?: null | components["schemas"]["FileObjectDetails"];
            imageAvatar512x512?: null | components["schemas"]["FileObjectDetails"];
            imageBanner1500x500?: null | components["schemas"]["FileObjectDetails"];
            imageWide1280x720?: null | components["schemas"]["FileObjectDetails"];
        };
        JsonElement: unknown;
        LanguageListItem: {
            /** Format: int32 */
            id: number | string;
            language: string;
        };
        /** @enum {unknown} */
        ListSortOption: "TitleAsc" | "TitleDesc" | "CreatedAtDesc" | "CreatedAtAsc";
        LoginRequest: {
            username: string;
            password: string;
        };
        LoginResult: {
            token: string;
            user: components["schemas"]["UserInfo"];
        };
        /** @enum {unknown} */
        MediaSource: "Unknown" | "UserUpload" | "MORA" | "OTOTOY" | "CD" | "BluRay" | "Vinyl" | "YouTube" | "SoundCloud" | "Spotify" | "Twitter" | "Other";
        MultipartUploadPartInfo: {
            /** Format: int32 */
            partNumber: number | string;
            url: string;
        };
        MultipartUploadResults: {
            uploadId: string;
            /** Format: int64 */
            partSizeInBytes: number | string;
            parts: components["schemas"]["MultipartUploadPartInfo"][];
        };
        PartyAlias: {
            name: string;
            normalizedName: string;
        };
        PartyDetails: {
            /** Format: int32 */
            partyId: number | string;
            name: string;
            avatarImages?: null | components["schemas"]["ImageFileVariants"];
            country: components["schemas"]["CountryCode"];
            description: string;
            type?: components["schemas"]["PartyType"];
            kind: components["schemas"]["PartyKind"];
            gender?: components["schemas"]["PartyGender"];
            aliases: components["schemas"]["PartyAlias"][];
            externalInfoLinks: components["schemas"]["PartyExternalInfoLink"][];
            albums: components["schemas"]["AlbumListItem"][];
            appearsOnAlbums: components["schemas"]["AlbumListItem"][];
        };
        PartyExternalInfoLink: {
            type: components["schemas"]["PartyExternalInfoType"];
            url: string;
        };
        /** @enum {unknown} */
        PartyExternalInfoType: "Spotify" | "Twitter" | "OfficialWebsite" | "YouTube" | "YouTubeMusic" | "Instagram" | "AppleMusic" | "Mora" | "Ototoy";
        /** @enum {unknown} */
        PartyGender: "Unknown" | "Male" | "Female";
        PartyImageRequest: {
            file: components["schemas"]["FileRequest"];
            croppedArea?: null | components["schemas"]["FileCroppedAreaRequest"];
        };
        PartyItems: {
            /** Format: int32 */
            partyId: number | string;
            name: string;
            normalizedName: string;
            coverUrl: string;
            country: components["schemas"]["CountryCode"];
            type?: components["schemas"]["PartyType"];
            kind: components["schemas"]["PartyKind"];
            gender?: components["schemas"]["PartyGender"];
            /** Format: double */
            similarity?: number | string;
            /** Format: int32 */
            albumCount: number | string;
            aliases: components["schemas"]["PartyAlias"][];
        };
        /** @enum {unknown} */
        PartyKind: "Human" | "VTuber" | "Vocaloid";
        /** @enum {unknown} */
        PartyType: "Individual" | "Group" | "Project";
        PasskeyDeleteRequest: {
            id?: string;
        };
        PasskeyDto: {
            id: string;
            name: string;
            /** Format: date-time */
            createdAt: string;
            transports: string[];
            deviceType: string;
        };
        PasskeyEditRequest: {
            id?: string;
            name?: string;
        };
        PendingOriginalFileResult: {
            /** Format: int32 */
            fileId: number | string;
            /** Format: uuid */
            fileObjectId: string;
            fileName: string;
            blake3Hash: string;
            processingStatus: components["schemas"]["FileProcessingStatus"];
            /** Format: date-time */
            createdAt: string;
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
        };
        RerunConcertWorkerRequest: {
            /** Format: uuid */
            objectId: string;
        };
        RerunPartyInfoEnrichmentWorkerRequest: {
            /** Format: int32 */
            partyId: number | string;
        };
        /** @enum {unknown} */
        Roles: "Admin" | "Uploader" | "User" | "Owner";
        SearchResult: {
            albums: components["schemas"]["AlbumListItem"][];
            concerts: components["schemas"]["ConcertListItem"][];
            parties: components["schemas"]["PartyItems"][];
        };
        StartUploadResult: {
            blake3Hash: string;
            fileObject: components["schemas"]["PendingOriginalFileResult"];
            multipartUpload: components["schemas"]["MultipartUploadResults"];
        };
        TrackAudioDetails: {
            /** Format: int32 */
            rank: number | string;
            pinned: boolean;
            source: components["schemas"]["MediaSource"];
            sourceUrl?: null | string;
            file: components["schemas"]["TrackAudioFileVariants"];
        };
        TrackAudioFileVariants: {
            original: components["schemas"]["FileObjectDetails"];
            taggedOriginal?: null | components["schemas"]["FileObjectDetails"];
            opus96?: null | components["schemas"]["FileObjectDetails"];
            waveformB8Pixel20?: null | components["schemas"]["FileObjectDetails"];
        };
        TrackAudioRequest: {
            file: components["schemas"]["FileRequest"];
            /** Format: int32 */
            rank?: number | string;
            pinned?: boolean;
            source?: components["schemas"]["MediaSource"];
            sourceUrl?: null | string;
        };
        /** @enum {unknown} */
        TrackContentType: "Music" | "MC" | "Interlude" | "Intro";
        TrackPartyCredit: {
            /** Format: int32 */
            partyId: number | string;
            name: string;
            type: components["schemas"]["PartyType"];
            creditType: components["schemas"]["CreditType"];
            avatar: components["schemas"]["ImageFileVariants"];
        };
        /** @enum {unknown} */
        TrackVersionType: "Original" | "Instrumental" | "Remix" | "Live" | "Acoustic" | "RadioEdit" | "Demo" | "Other";
        UpdateUserRequest: {
            username?: null | string;
            password?: null | string;
            role?: null | components["schemas"]["Roles"];
        };
        UserInfo: {
            id: string;
            userName: string;
            roles: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
