/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/albums/{id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AlbumSummary"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/albums": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AlbumListItem"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateAlbumRequest"][];
                    "text/json": components["schemas"]["CreateAlbumRequest"][];
                    "application/*+json": components["schemas"]["CreateAlbumRequest"][];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CreateAlbumResult"][];
                        "application/json": components["schemas"]["CreateAlbumResult"][];
                        "text/json": components["schemas"]["CreateAlbumResult"][];
                    };
                };
                /** @description Multi-Status */
                207: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CreateAlbumResult"][];
                        "application/json": components["schemas"]["CreateAlbumResult"][];
                        "text/json": components["schemas"]["CreateAlbumResult"][];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CreateAlbumResult"][];
                        "application/json": components["schemas"]["CreateAlbumResult"][];
                        "text/json": components["schemas"]["CreateAlbumResult"][];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/albums/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AlbumDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                    "text/json": components["schemas"]["LoginRequest"];
                    "application/*+json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["LoginResult"];
                        "application/json": components["schemas"]["LoginResult"];
                        "text/json": components["schemas"]["LoginResult"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/bot-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/languages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LanguageListItem"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["UserInfo"];
                        "application/json": components["schemas"]["UserInfo"];
                        "text/json": components["schemas"]["UserInfo"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/parties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PartyItems"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreatePartyRequest"];
                    "text/json": components["schemas"]["CreatePartyRequest"];
                    "application/*+json": components["schemas"]["CreatePartyRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreatePartyResult"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/Init": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateUploadRequest"];
                    "text/json": components["schemas"]["CreateUploadRequest"];
                    "application/*+json": components["schemas"]["CreateUploadRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MultipartUploadResults"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CompleteUploadRequest"];
                    "text/json": components["schemas"]["CompleteUploadRequest"];
                    "application/*+json": components["schemas"]["CompleteUploadRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AlbumCoverDetails: {
            album: components["schemas"]["AlbumCoverVariant"][];
            discs: components["schemas"]["AlbumDiscCoverDetails"][];
        };
        AlbumCoverVariant: {
            variant: components["schemas"]["FileObjectVariant"];
            url: string;
        };
        AlbumDetails: {
            /** Format: int32 */
            albumId: number | string;
            title: string;
            type: components["schemas"]["AlbumType"];
            /** Format: date-time */
            releaseDate?: null | string;
            /** Format: int32 */
            totalTrackCount: number | string;
            /** Format: int32 */
            totalDurationInMs: number | string;
            cover: components["schemas"]["AlbumCoverDetails"];
            credits: components["schemas"]["AlbumPartyCredit"][];
            discs: components["schemas"]["AlbumDiscDetails"][];
        };
        AlbumDiscCoverDetails: {
            /** Format: int32 */
            albumDiscId: number | string;
            /** Format: int32 */
            discNumber: number | string;
            variants: components["schemas"]["AlbumCoverVariant"][];
        };
        AlbumDiscDetails: {
            /** Format: int32 */
            albumDiscId: number | string;
            /** Format: int32 */
            discNumber: number | string;
            subtitle?: string;
            tracks: components["schemas"]["AlbumTrackDetails"][];
        };
        AlbumDiscRequest: {
            /** Format: int32 */
            discNumber: number | string;
            subtitle?: string;
            image?: null | components["schemas"]["AlbumImageRequest"];
            tracks: components["schemas"]["AlbumTrackRequest"][];
        };
        AlbumImageRequest: {
            clientReferenceId: string;
            file: components["schemas"]["FileRequest"];
            description?: string;
            croppedArea?: null | components["schemas"]["FileCroppedAreaRequest"];
        };
        AlbumListArtist: {
            /** Format: int32 */
            partyId: number | string;
            name: string;
        };
        AlbumListItem: {
            /** Format: int32 */
            albumId: number | string;
            title: string;
            description?: string;
            type: components["schemas"]["AlbumType"];
            /** Format: date-time */
            releaseDate?: null | string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            coverVariants?: components["schemas"]["AlbumCoverVariant"][];
            discCovers?: components["schemas"]["AlbumDiscCoverDetails"][];
            artists: components["schemas"]["AlbumListArtist"][];
            /** Format: int32 */
            trackCount: number | string;
            /** Format: int32 */
            totalDurationInMs: number | string;
        };
        AlbumPartyCredit: {
            /** Format: int32 */
            partyId: number | string;
            name: string;
            type: components["schemas"]["PartyType"];
            creditType: components["schemas"]["CreditType"];
            avatar: components["schemas"]["PartyImage"][];
        };
        AlbumSummary: {
            title: string;
            credits: string[];
            coverUrl: string;
        };
        AlbumTrackDetails: {
            /** Format: int32 */
            trackId: number | string;
            /** Format: int32 */
            trackNumber: number | string;
            title: string;
            /** Format: int32 */
            durationInMs: number | string;
            contentType: components["schemas"]["TrackContentType"];
            versionType: components["schemas"]["TrackVersionType"];
            /** Format: int32 */
            basedOnTrackId?: null | number | string;
            credits: components["schemas"]["TrackPartyCredit"][];
            audios: components["schemas"]["TrackAudioDetails"][];
        };
        AlbumTrackRequest: {
            clientTempTrackId: string;
            /** Format: int32 */
            trackNumber: number | string;
            title: string;
            description?: string;
            /** Format: int32 */
            durationInMs: number | string;
            /** Format: int32 */
            languageId?: null | number | string;
            contentType?: components["schemas"]["TrackContentType"];
            versionType?: components["schemas"]["TrackVersionType"];
            /** Format: int32 */
            basedOnTrackId?: null | number | string;
            credits: components["schemas"]["CreditRequest"][];
            audios: components["schemas"]["TrackAudioRequest"][];
        };
        /** @enum {unknown} */
        AlbumType: "Album" | "Single" | "Compilation" | "Live" | "Soundtrack" | "Remix" | "Other";
        CompleteMultipartUploadPart: {
            /** Format: int32 */
            partNumber: number | string;
            eTag: string;
        };
        CompleteMultipartUploadRequest: {
            uploadId: string;
            parts: components["schemas"]["CompleteMultipartUploadPart"][];
        };
        CompleteUploadRequest: {
            /** Format: uuid */
            fileObjectId: string;
            multipart?: null | components["schemas"]["CompleteMultipartUploadRequest"];
        };
        /** @enum {unknown} */
        CountryCode: "XX" | "HK" | "JP" | "KR" | "US" | "CN" | "TW";
        CreateAlbumImageUploadItemResult: {
            clientReferenceId: string;
            /** Format: int32 */
            discNumber?: null | number | string;
            /** Format: uuid */
            fileObjectId: string;
            blake3Hash: string;
            fileName: string;
            uploadUrl: string;
        };
        CreateAlbumRequest: {
            clientTempAlbumId: string;
            title: string;
            description?: string;
            type: components["schemas"]["AlbumType"];
            /** Format: int32 */
            languageId?: null | number | string;
            /** Format: date-time */
            releaseDate?: null | string;
            credits: components["schemas"]["CreditRequest"][];
            image?: null | components["schemas"]["AlbumImageRequest"];
            discs: components["schemas"]["AlbumDiscRequest"][];
        };
        CreateAlbumResult: {
            clientTempAlbumId: string;
            albumTitle: string;
            isSuccess?: boolean;
            errorMessage?: null | string;
            upload?: null | components["schemas"]["CreateAlbumUploadResult"];
        };
        CreateAlbumTrackUploadItemResult: {
            /** Format: uuid */
            fileObjectId: string;
            blake3Hash: string;
            fileName: string;
            multipartUploadInfo: components["schemas"]["MultipartUploadResults"];
        };
        CreateAlbumUploadResult: {
            albumTitle: string;
            images?: components["schemas"]["CreateAlbumImageUploadItemResult"][];
            tracks?: components["schemas"]["CreateAlbumTrackUploadItemResult"][];
        };
        CreatePartyRequest: {
            name: string;
            type: components["schemas"]["PartyType"];
            kind: components["schemas"]["PartyKind"];
            country: components["schemas"]["CountryCode"];
            musicBrainzID?: null | string;
            avatar?: null | components["schemas"]["PartyImageRequest"];
            banner?: null | components["schemas"]["PartyImageRequest"];
        };
        CreatePartyResult: {
            /** Format: int32 */
            partyId: number | string;
        };
        CreateUploadRequest: {
            /** Format: int32 */
            fileId: number | string;
        };
        CreditRequest: {
            /** Format: int32 */
            partyId: number | string;
            credit: components["schemas"]["CreditType"];
        };
        /** @enum {unknown} */
        CreditType: "Artist";
        FileCroppedAreaRequest: {
            /** Format: int32 */
            width: number | string;
            /** Format: int32 */
            height: number | string;
            /** Format: int32 */
            x: number | string;
            /** Format: int32 */
            y: number | string;
        };
        FileObjectDetails: {
            /** Format: uuid */
            id: string;
            url: string;
            variant: components["schemas"]["FileObjectVariant"];
            /** Format: int64 */
            sizeInBytes: number | string;
            mimeType: string;
            container: string;
            extension: string;
            codec?: null | string;
            /** Format: int32 */
            width?: null | number | string;
            /** Format: int32 */
            height?: null | number | string;
            /** Format: int32 */
            audioSampleRate?: null | number | string;
            /** Format: int32 */
            bitrate?: null | number | string;
            /** Format: double */
            frameRate?: null | number | string;
            /** Format: int32 */
            durationInMs?: null | number | string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @enum {unknown} */
        FileObjectVariant: "Original" | "TaggedOriginal" | "Opus96" | "WaveformB8Pixel20" | "OriginalDash" | "DashAV1" | "Thumbnail640x360" | "AttachedPicture" | "SubtitleVtt" | "SubtitleSup";
        FileRequest: {
            blake3Hash: string;
            mimeType: string;
            /** Format: int64 */
            sizeInBytes: number | string;
            container: string;
            extension: string;
            codec?: null | string;
            lossless?: boolean;
            /** Format: int32 */
            audioChannels?: null | number | string;
            /** Format: int32 */
            bitsPerSample?: null | number | string;
            /** Format: int32 */
            width?: null | number | string;
            /** Format: int32 */
            height?: null | number | string;
            /** Format: int32 */
            audioSampleRate?: null | number | string;
            /** Format: int32 */
            bitrate?: null | number | string;
            /** Format: double */
            frameRate?: null | number | string;
            /** Format: int32 */
            durationInMs?: null | number | string;
            originalFileName: string;
        };
        LanguageListItem: {
            /** Format: int32 */
            id: number | string;
            language: string;
        };
        LoginRequest: {
            username: string;
            password: string;
        };
        LoginResult: {
            token: string;
            user: components["schemas"]["UserInfo"];
        };
        /** @enum {unknown} */
        MediaSource: "Unknown" | "UserUpload" | "MORA" | "OTOTOY" | "CD" | "BluRay" | "Vinyl" | "YouTube" | "SoundCloud" | "Spotify" | "Twitter" | "Other";
        MultipartUploadPartInfo: {
            /** Format: int32 */
            partNumber: number | string;
            url: string;
        };
        MultipartUploadResults: {
            uploadId: string;
            /** Format: int64 */
            partSizeInBytes: number | string;
            parts: components["schemas"]["MultipartUploadPartInfo"][];
        };
        PartyAlias: {
            name: string;
            normalizedName: string;
        };
        PartyImage: {
            variant: components["schemas"]["FileObjectVariant"];
            url: string;
        };
        PartyImageRequest: {
            file: components["schemas"]["FileRequest"];
            croppedArea?: null | components["schemas"]["FileCroppedAreaRequest"];
        };
        PartyItems: {
            /** Format: int32 */
            partyId: number | string;
            name: string;
            normalizedName: string;
            country: components["schemas"]["CountryCode"];
            type?: components["schemas"]["PartyType"];
            kind: components["schemas"]["PartyKind"];
            aliases: components["schemas"]["PartyAlias"][];
        };
        /** @enum {unknown} */
        PartyKind: "Human" | "VTuber" | "Vocaloid";
        /** @enum {unknown} */
        PartyType: "Individual" | "Group" | "Project";
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
        };
        TrackAudioDetails: {
            /** Format: int32 */
            rank: number | string;
            pinned: boolean;
            file: components["schemas"]["TrackAudioFileVariants"];
        };
        TrackAudioFileVariants: {
            original: components["schemas"]["FileObjectDetails"];
            taggedOriginal?: null | components["schemas"]["FileObjectDetails"];
            opus96?: null | components["schemas"]["FileObjectDetails"];
            waveformB8Pixel20?: null | components["schemas"]["FileObjectDetails"];
        };
        TrackAudioRequest: {
            file: components["schemas"]["FileRequest"];
            /** Format: int32 */
            rank?: number | string;
            pinned?: boolean;
            source?: components["schemas"]["MediaSource"];
            sourceUrl?: null | string;
        };
        /** @enum {unknown} */
        TrackContentType: "Music" | "MC" | "Interlude" | "Intro";
        TrackPartyCredit: {
            /** Format: int32 */
            partyId: number | string;
            name: string;
            type: components["schemas"]["PartyType"];
            creditType: components["schemas"]["CreditType"];
            avatar: components["schemas"]["PartyImage"][];
        };
        /** @enum {unknown} */
        TrackVersionType: "Original" | "Instrumental" | "Remix" | "Live" | "Acoustic" | "RadioEdit" | "Demo" | "Other";
        UserInfo: {
            id: string;
            userName: string;
            roles: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
