/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as PublicLoginIndexRouteImport } from './routes/_public/login/index'
import { Route as AuthedPartiesIndexRouteImport } from './routes/_authed/parties/index'
import { Route as AuthedCreateIndexRouteImport } from './routes/_authed/create/index'
import { Route as AuthedAlbumsIndexRouteImport } from './routes/_authed/albums/index'
import { Route as AuthedPartiesIdRouteImport } from './routes/_authed/parties/$id'
import { Route as AuthedAlbumsIdRouteImport } from './routes/_authed/albums/$id'

const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const PublicLoginIndexRoute = PublicLoginIndexRouteImport.update({
  id: '/_public/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedPartiesIndexRoute = AuthedPartiesIndexRouteImport.update({
  id: '/parties/',
  path: '/parties/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedCreateIndexRoute = AuthedCreateIndexRouteImport.update({
  id: '/create/',
  path: '/create/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAlbumsIndexRoute = AuthedAlbumsIndexRouteImport.update({
  id: '/albums/',
  path: '/albums/',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedPartiesIdRoute = AuthedPartiesIdRouteImport.update({
  id: '/parties/$id',
  path: '/parties/$id',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedAlbumsIdRoute = AuthedAlbumsIdRouteImport.update({
  id: '/albums/$id',
  path: '/albums/$id',
  getParentRoute: () => AuthedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/albums/$id': typeof AuthedAlbumsIdRoute
  '/parties/$id': typeof AuthedPartiesIdRoute
  '/albums/': typeof AuthedAlbumsIndexRoute
  '/create/': typeof AuthedCreateIndexRoute
  '/parties/': typeof AuthedPartiesIndexRoute
  '/login/': typeof PublicLoginIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthedIndexRoute
  '/albums/$id': typeof AuthedAlbumsIdRoute
  '/parties/$id': typeof AuthedPartiesIdRoute
  '/albums': typeof AuthedAlbumsIndexRoute
  '/create': typeof AuthedCreateIndexRoute
  '/parties': typeof AuthedPartiesIndexRoute
  '/login': typeof PublicLoginIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/albums/$id': typeof AuthedAlbumsIdRoute
  '/_authed/parties/$id': typeof AuthedPartiesIdRoute
  '/_authed/albums/': typeof AuthedAlbumsIndexRoute
  '/_authed/create/': typeof AuthedCreateIndexRoute
  '/_authed/parties/': typeof AuthedPartiesIndexRoute
  '/_public/login/': typeof PublicLoginIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/albums/$id'
    | '/parties/$id'
    | '/albums/'
    | '/create/'
    | '/parties/'
    | '/login/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/albums/$id'
    | '/parties/$id'
    | '/albums'
    | '/create'
    | '/parties'
    | '/login'
  id:
    | '__root__'
    | '/_authed'
    | '/_authed/'
    | '/_authed/albums/$id'
    | '/_authed/parties/$id'
    | '/_authed/albums/'
    | '/_authed/create/'
    | '/_authed/parties/'
    | '/_public/login/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  PublicLoginIndexRoute: typeof PublicLoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_public/login/': {
      id: '/_public/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof PublicLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/parties/': {
      id: '/_authed/parties/'
      path: '/parties'
      fullPath: '/parties/'
      preLoaderRoute: typeof AuthedPartiesIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/create/': {
      id: '/_authed/create/'
      path: '/create'
      fullPath: '/create/'
      preLoaderRoute: typeof AuthedCreateIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/albums/': {
      id: '/_authed/albums/'
      path: '/albums'
      fullPath: '/albums/'
      preLoaderRoute: typeof AuthedAlbumsIndexRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/parties/$id': {
      id: '/_authed/parties/$id'
      path: '/parties/$id'
      fullPath: '/parties/$id'
      preLoaderRoute: typeof AuthedPartiesIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/albums/$id': {
      id: '/_authed/albums/$id'
      path: '/albums/$id'
      fullPath: '/albums/$id'
      preLoaderRoute: typeof AuthedAlbumsIdRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
  }
}

interface AuthedRouteRouteChildren {
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedAlbumsIdRoute: typeof AuthedAlbumsIdRoute
  AuthedPartiesIdRoute: typeof AuthedPartiesIdRoute
  AuthedAlbumsIndexRoute: typeof AuthedAlbumsIndexRoute
  AuthedCreateIndexRoute: typeof AuthedCreateIndexRoute
  AuthedPartiesIndexRoute: typeof AuthedPartiesIndexRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedAlbumsIdRoute: AuthedAlbumsIdRoute,
  AuthedPartiesIdRoute: AuthedPartiesIdRoute,
  AuthedAlbumsIndexRoute: AuthedAlbumsIndexRoute,
  AuthedCreateIndexRoute: AuthedCreateIndexRoute,
  AuthedPartiesIndexRoute: AuthedPartiesIndexRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  PublicLoginIndexRoute: PublicLoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
