[package]
name = "music_presence"
version = "1.0.0"
edition = "2024"

[lib]
name = "music_presence"
path = "src/lib.rs"

[dependencies]
tokio-tungstenite = { version = "*", features = ["rustls-tls-webpki-roots"] }
discord-presence = "2.1"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time"] }
futures-util = "0.3.31"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
http = "1.3.1"
reqwest = { version = "0.12", features = ["json"] }
js-sys = "0.3.81"
rustls = {version = "0.23.32", default-features = false, features = ["ring"] }
