name: Build & Publish (GHCR)

on:
  push:
    branches: ["master"]
  tags:
    - "v*.*.*"
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            backend:
              - 'apps/backend/**'
              - 'packages/**'
            web:
              - 'apps/web/**'
              - 'packages/**'
      # backend
      - name: Docker metadata for backend
        id: meta-backend
        if: steps.changes.outputs.backend == 'true'
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-backend
          tags: |
            type=semver,pattern={{version}},enable=${{ startsWith(github.ref, 'refs/tags/') }}
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/master' }}
            type=sha

      - name: Build and push Docker image (backend)
        id: push-backend
        if: steps.changes.outputs.backend == 'true'
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          file: apps/backend/Dockerfile
          push: true
          tags: ${{ steps.meta-backend.outputs.tags }}
          labels: ${{ steps.meta-backend.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Generate artifact attestation (backend)
        uses: actions/attest-build-provenance@v3
        if: steps.changes.outputs.backend == 'true'
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}-backend
          subject-digest: ${{ steps.push-backend.outputs.digest }}
          push-to-registry: true
        # web
      - name: Docker metadata for web
        id: meta-web
        if: steps.changes.outputs.web == 'true'
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-web
          tags: |
            type=semver,pattern={{version}},enable=${{ startsWith(github.ref, 'refs/tags/') }}
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/master' }}
            type=sha

      - name: Build and push Docker image (web)
        id: push-web
        if: steps.changes.outputs.web == 'true'
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          file: apps/web/Dockerfile
          push: true
          tags: ${{ steps.meta-web.outputs.tags }}
          labels: ${{ steps.meta-web.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Generate artifact attestation (web)
        uses: actions/attest-build-provenance@v3
        if: steps.changes.outputs.web == 'true'
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}-web
          subject-digest: ${{ steps.push-web.outputs.digest }}
          push-to-registry: true
